### ISSUE TITLE
Does this support the new class syntax? 

### ISSUE THREAD

**Issue by thedumbtechguy** [Envek/graphql-preload#2]
Just wondering if we have to use the old style of defining queries and models or if this fork supports the new syntax.

If it does, do you have any examples? 

Hope you're keeping safe during these troubling times.
Thanks

**Comment by Envek** [comment]
Ah, README is pretty old (probably, I haven't touched it at all).

Yes, it supports new class syntax. Look at the tests for example:
https://github.com/Envek/graphql-preload/blob/d2abaab01548b2049f73d01594f2eab37eea0fa3/spec/support/graphql_schema.rb#L19-L26

Also you can use block-style definitions:
```ruby
class Types::Product < Types::BaseObject
  field :id, ID, null: false
  field :title, String, null: true

  field :variations, [Types::Product::Variation], null: false do
    preload :variations
    preload_scope ->(*) { VARIATION_RELATION }
  end

  VARIATION_RELATION = ::Product::Variation.order(id: :asc)
end
```
