### ISSUE TITLE
Ordering in schema

### ISSUE THREAD

**Issue by jjb** [Envek/graphql-preload#5]
Hello - thank you for maintaining this gem!

In the graphql-batch docs: https://github.com/Shopify/graphql-batch#schema-configuration

"Use GraphQL::Batch as a plugin in your schema _after_ specifying the mutation so that GraphQL::Batch can extend the mutation fields to clear the cache after they are resolved "

Their examples also show GraphQL::Batch coming after specifying the QueryType

In the graphql-preload docs and tests, mutations aren't shown, but batch and preload always come _before_ specifying the querytype

does this ordering matter? is it okay if preload comes _after_ query and mutation?

Thanks!

**Comment by Envek** [comment]
Hey! To be honest, I don't really maintain (or even use) this gem recently.

And I don't know answer to your question too. And don't have capacity to dig into it either.

Consider moving to [Dataloader that is built-in in GraphQL-Ruby since 1.12](https://github.com/rmosolgo/graphql-ruby/pull/3264).

**Comment by jjb** [comment]
Thanks for the suggestion!
